spring:
  application:
    name: spring-boot-email-service
  config:
    import:
    - optional:configtree:/run/secrets/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email-username}
    password: ${email-password}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
            

