spring:
  application:
    name: spring-boot-email-service
  mail:
    host: smtp.xxx.com
    port: 587
    username: xxx@xxx.com
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
            

